### ISSUE TITLE
Figure out how to deploy API 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#27]

**Comment by Function-0** [comment]
- Created new repo [Mechanic Checker API](https://github.com/COMP231W21-G5/Mechanic-Checker-API) for the Nodejs API. An ammendement will be made in the TAC Report explaining the change from Django to Nodejs.
- Created AWS Codepipeline for CI/CD. At the moment whenever a push is made to [develop-ibrahim-test1-nodejs](https://github.com/COMP231W21-G5/Mechanic-Checker-API/tree/develop-ibrahim-test1-nodejs) the CI/CD AWS Codepipeline activates and deploys the code.
- Created AWS Elastic Beanstalk for managing EC2 instance deployments of the Mechanic Checker API repo

Total Time: 7hrs
