### ISSUE TITLE
Figure out how to deploy API Alibaba 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#33]

**Comment by Function-0** [comment]
- Created a GitHub Action [Deploy Mechanic Checker Netcore](https://github.com/COMP231W21-G5/Mechanic-Checker/actions/workflows/main.yml) as a CI/CD pipeline to: do a dotnet release, zip said release, and then deploy it to AWS Elastic Beanstalk. The [main.yml](https://github.com/COMP231W21-G5/Mechanic-Checker/blob/develop/.github/workflows/main.yml) script has been set up to dynamically create the appsettings.json file with the MySQL database connection string.
- Created GitHub action secrets for AWS secret keys and MySQL connection strings

Total Time: 4hrs
