### ISSUE TITLE
Figure out how to deploy API Amazon 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#39]

**Comment by Function-0** [comment]
- Added [CI-CD Deployment Pipeline Documentation](https://github.com/COMP231W21-G5/Mechanic-Checker/wiki/CI-CD-Deployment-Pipeline)
- Added GitHub deployment environment statuses for [Mechanic Checker](https://github.com/COMP231W21-G5/Mechanic-Checker) repo and [Mechanic Checker API](https://github.com/COMP231W21-G5/Mechanic-Checker-API) repo

2 hours
