### ISSUE TITLE
Documentation for signing up as a seller to the mechanic checker app 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#50]

**Comment by Function-0** [comment]
Sign Up User Documentation: https://github.com/COMP231W21-G5/Mechanic-Checker/wiki/Sign-Up
Reset Password User Documentation: https://github.com/COMP231W21-G5/Mechanic-Checker/wiki/Reset-Password
Sign In User Documentation: https://github.com/COMP231W21-G5/Mechanic-Checker/wiki/Sign-In
